# Generated by Django 4.0.6 on 2022-08-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_email_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='connect',
            field=models.TextField(null=True),
        ),
    ]
