# Generated by Django 4.0.6 on 2022-08-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_connect'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='family',
            field=models.TextField(null=True),
        ),
    ]
