# Generated by Django 4.0.6 on 2022-08-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kind',
            field=models.BooleanField(null=True),
        ),
    ]
