# Generated by Django 4.0.6 on 2022-08-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinmoney', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinmoney',
            name='receiver',
            field=models.CharField(default='Nan', max_length=100),
            preserve_default=False,
        ),
    ]
