# Generated by Django 4.0.6 on 2022-08-11 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='receiver',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='reward',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
