# Generated by Django 4.0.6 on 2022-08-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0003_missionlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionlist',
            name='section',
            field=models.CharField(default='Nan', max_length=1000),
            preserve_default=False,
        ),
    ]
