# Generated by Django 4.0.6 on 2022-08-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0004_missionlist_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=20)),
                ('ranking', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(db_column='phoneNumber', max_length=20)),
            ],
            options={
                'db_table': 'Card',
                'managed': False,
            },
        ),
    ]
